steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=dockerpassword --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/decrypted-data.txt" ]

- name: gcr.io/$PROJECT_ID/remote-builder
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image-project centos-cloud --image-family centos-7 --preemptible --machine-type e2-medium --boot-disk-type=pd-ssd
    - ZONE=asia-northeast2-a
    - USERNAME=cloud-user

    - >
      COMMAND=id && 
      pwd && 
      cd workspace &&
      sudo bash -xe execroot.sh

timeout: 3600s
